### ISSUE TITLE
Missing headers?

### ISSUE THREAD

**Issue by aazhevsky** [mradermaxlol/HWY600-kernel#15]
Hi!
I can not find a declaration of some constants, like AUDIO_MODE_IN_CALL_EXTERNAL. Could you, please, suggest where can I find them?

**Comment by mradermaxlol** [comment]
@aazhevsky, I don't think they're meant to be in **this** particular source code, as it's an adaptation of official MTK source for the target device (Huawey Ascend Y600), AFAIK. Other than that, I don't really know (and don't want to, heh) why are they missing and where you can find them, sorry >_<
You can try asking @AlexXXX12389, maybe he's got some info about headers out here.

(spoiler: this repo is not really maintained at all - for various obvious reasons, so I don't think you'll be able to find help here)

**Comment by aazhevsky** [comment]
Thank you for the hint.
Have a nice day!
